# Generated by Django 3.2.6 on 2021-08-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_seasonal',
        ),
    ]
