# Generated by Django 3.2.6 on 2021-08-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_description_ingredient_unit_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperequirment',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
