# Generated by Django 3.2.6 on 2021-08-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_menuitem_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperequirment',
            old_name='amount',
            new_name='required_amount',
        ),
    ]
