# Generated by Django 3.2.6 on 2021-08-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_amount_reciperequirment_required_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciperequirment',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.menuitem'),
        ),
    ]
