# Generated by Django 3.2.6 on 2021-08-27 16:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
