# Generated by Django 3.2.6 on 2021-08-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20210827_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='item_name',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.menuitem'),
        ),
    ]
