# Generated by Django 3.2.6 on 2021-09-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210903_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.register'),
            preserve_default=False,
        ),
    ]
