# Generated by Django 3.2.6 on 2021-09-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_purchase_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='register',
        ),
    ]
