# Generated by Django 3.2.6 on 2021-09-06 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_purchase_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='register',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='inventory.register'),
        ),
    ]
